#!/usr/bin/env python3
"""Generate tests/data/exp64_reference.txt: correctly rounded exp.

The reference is independent of every libm: each input is an exact binary
double, `mpmath` evaluates exp at 2400 bits, and the result is rounded to the
nearest double (ties to even) by comparing the three candidate doubles around
it in high precision.

A platform libm is not usable as the reference even when it happens to be
correctly rounded on the machine that runs the test: whether the measured
difference stays inside the documented bound would then depend on which libm
the test was linked with. `exp64` is within 2 ulp of correctly rounded by
design, so a 1 ulp reference error is a quarter of the budget.

Inputs (all finite): the overflow and underflow thresholds and their
neighbours, the two exponent-scale boundaries (`k > 1023`, `k < -1022`, where
the result is built with two multiplications), the subnormal tail, the ends of
the reduced range (near multiples of ln2/2), small arguments where the result
is 1 plus a few ulp, integers, and log-uniform values across the whole
meaningful range.

Each line: `<x bits> <exp(x) bits>`, 16 hex digits each.

Usage: `uv run --with mpmath python3 scripts/gen_exp64_reference.py`
(or any Python with mpmath installed). The output is deterministic.
"""

from __future__ import annotations

import math
import os
import random
import struct

import mpmath

mpmath.mp.prec = 2400

# src/double.rs::exp64
OVERFLOW = 709.782_712_893_384
UNDERFLOW = -745.133_219_101_941_1
LN2 = 0.693_147_180_559_945_309_417_232_121_458_176_568


def bits(x: float) -> int:
    return struct.unpack("<Q", struct.pack("<d", x))[0]


def from_bits(b: int) -> float:
    return struct.unpack("<d", struct.pack("<Q", b))[0]


def round_nearest(v: mpmath.mpf) -> float:
    """The double nearest to v (ties to even), decided in high precision."""
    c = float(v)
    best = None
    for cand in (math.nextafter(c, -math.inf), c, math.nextafter(c, math.inf)):
        d = abs(mpmath.mpf(cand) - v)
        key = (d, bits(cand) & 1)  # on an exact tie, the even mantissa wins
        if best is None or key < best[0]:
            best = (key, cand)
    return best[1]


def neighbours(x: float, n: int = 3) -> list[float]:
    out = [x]
    for k in range(1, n + 1):
        out.append(from_bits(bits(x) + k) if x > 0 else from_bits(bits(x) - k))
        out.append(from_bits(bits(x) - k) if x > 0 else from_bits(bits(x) + k))
    return out


def inputs() -> list[float]:
    rng = random.Random(20261007)
    xs: list[float] = [0.0]
    # the thresholds and the exponent-scale boundaries
    for t in (OVERFLOW, UNDERFLOW, 1023 * LN2, -1022 * LN2, -1074 * LN2, 709.0, -708.0):
        xs += neighbours(t, 4)
    # the subnormal tail: between -708.4 and -745.1 the result is subnormal
    for i in range(240):
        xs.append(-708.0 - 37.5 * i / 239)
    # the ends of the reduced range: x = (k + 1/2)·ln2 puts |r| at its maximum
    for k in range(-1070, 1025, 7):
        for d in (-0.5, -0.25, 0.0, 0.25, 0.5):
            x = (k + d) * LN2
            if UNDERFLOW < x < OVERFLOW:
                xs.append(x)
    # small arguments: exp(x) = 1 + x + ... and the 2^-28 shortcut region
    for e in range(0, 60):
        xs += [math.ldexp(1.0, -e), -math.ldexp(1.0, -e)]
    xs += [from_bits(1), -from_bits(1), 5e-324]
    # integers and simple values
    xs += [float(i) for i in range(-50, 51)]
    xs += [1.0, -1.0, LN2, -LN2, math.e, -math.e]
    # log-uniform over the meaningful range, both signs
    for _ in range(900):
        xs.append(rng.uniform(UNDERFLOW, OVERFLOW))
    out, seen = [], set()
    for x in xs:
        b = bits(x)
        if b not in seen and math.isfinite(x):
            seen.add(b)
            out.append(x)
    return sorted(out)


def main() -> None:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "tests", "data", "exp64_reference.txt")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    lines = []
    for x in inputs():
        v = round_nearest(mpmath.exp(mpmath.mpf(x)))
        if not math.isfinite(v):
            continue  # above the overflow threshold the result is +inf
        lines.append(f"{bits(x):016x} {bits(v):016x}")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("# x exp(x): IEEE 754 binary64 bits, correctly rounded (mpmath, 2400 bits)\n")
        f.write("# generated by scripts/gen_exp64_reference.py\n")
        f.write("# Not produced by any libm: a libm that is correctly rounded on one\n")
        f.write("# machine and a ulp off on another would make the bound depend on the\n")
        f.write("# machine rather than on this crate.\n")
        f.write("\n".join(lines) + "\n")
    print(f"{len(lines)} inputs -> {path}")


if __name__ == "__main__":
    main()
