#!/usr/bin/env python3
"""Generate tests/data/tan64_reference.txt: correctly rounded tan.

The reference is independent of every libm: each input is an exact binary
double, `mpmath` evaluates tan at 2400 bits (enough to reduce any finite
double modulo pi/2 with more than 1300 bits to spare), and the result is
rounded to the nearest double (ties to even) by comparing the three candidate
doubles around it in high precision.

This matters more for the tangent than for sine and cosine: near a pole the
function is enormous, so an argument reduction that is a few bits short moves
the result by many ulp. A platform libm disagrees with the correctly rounded
value by about 1.0e5 ulp at x = 0x6404c96c11134d36, while another is within
2 ulp of it, which is why `tests/accuracy.rs` asserts against this table and
not against whatever libm the test happens to be linked with.

The inputs are the x column of tests/data/sin_cos64_reference.txt, so the two
tables cover the same arguments: small and medium, every branch threshold of
the fdlibm reduction, near multiples of pi/2, the hardest argument-reduction
cases per binade, and log-uniform huge values up to f64::MAX.

Each line: `<x bits> <tan bits>`, 16 hex digits each.

Usage: `uv run --with mpmath python3 scripts/gen_tan64_reference.py`
(or any Python with mpmath installed). The output is deterministic.
"""

from __future__ import annotations

import math
import os
import struct

import mpmath

mpmath.mp.prec = 2400


def bits(x: float) -> int:
    return struct.unpack("<Q", struct.pack("<d", x))[0]


def from_bits(b: int) -> float:
    return struct.unpack("<d", struct.pack("<Q", b))[0]


def round_nearest(v: mpmath.mpf) -> float:
    """The double nearest to v (ties to even), decided in high precision."""
    c = float(v)
    best = None
    for cand in (math.nextafter(c, -math.inf), c, math.nextafter(c, math.inf)):
        d = abs(mpmath.mpf(cand) - v)
        key = (d, bits(cand) & 1)  # on an exact tie, the even mantissa wins
        if best is None or key < best[0]:
            best = (key, cand)
    return best[1]


def inputs(root: str) -> list[float]:
    """The x column of the sine / cosine reference, in file order."""
    path = os.path.join(root, "tests", "data", "sin_cos64_reference.txt")
    xs = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            xs.append(from_bits(int(line.split()[0], 16)))
    if not xs:
        raise SystemExit(f"no inputs read from {path}")
    return xs


def main() -> None:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "tests", "data", "tan64_reference.txt")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    lines = []
    for x in inputs(root):
        t = round_nearest(mpmath.tan(mpmath.mpf(x)))
        if not math.isfinite(t):
            # no finite double has a tangent outside the double range, but say
            # so rather than writing an infinity into the table
            raise SystemExit(f"tan({x!r}) is not finite: {t!r}")
        lines.append(f"{bits(x):016x} {bits(t):016x}")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("# x tan(x): IEEE 754 binary64 bits, correctly rounded (mpmath, 2400 bits)\n")
        f.write("# generated by scripts/gen_tan64_reference.py\n")
        f.write("# The inputs are the x column of sin_cos64_reference.txt, so the two\n")
        f.write("# tables cover the same arguments. Not produced by any libm: one is\n")
        f.write("# ~1.0e5 ulp off at x = 0x6404c96c11134d36 and is not a reference.\n")
        f.write("\n".join(lines) + "\n")
    print(f"{len(lines)} inputs -> {path}")


if __name__ == "__main__":
    main()
