#!/usr/bin/env bash
# scripts/preflight.sh — local reproduction of the CI gates before `git push`.
# Generated by ~/claude-config/scripts/gen-preflight.py from the workflows below;
# every command is the one CI runs. A step this file does not cover is a step
# that can only fail remotely — when a workflow step is added, regenerate or
# add it here in the same commit. ~/.claude/hooks/pre-push-preflight.sh runs
# `--quick` before every push and blocks on failure.
#
# usage: scripts/preflight.sh [--quick]   (--quick skips the test / bench suites)
set -euo pipefail
cd "$(dirname "$0")/.."

quick=0
[[ "${1:-}" == "--quick" ]] && quick=1

step() { printf '\n\033[1;34m== %s\033[0m\n' "$*"; }
# `cargo clippy` reuses fresh `cargo check` artifacts and then lints nothing;
# touching the crate roots invalidates only this repo's fingerprints.
relint() { git ls-files | grep -E '(^|/)src/(lib|main)\.rs$' | xargs -r touch; }
need() { command -v "$1" >/dev/null 2>&1 || { echo "missing tool: $1 ($2)" >&2; exit 1; }; }
has_toolchain() { rustup toolchain list | grep -q "^$1"; }

# Steps CI runs that this file cannot reproduce locally (they can only fail remotely):
#   - ci.yml:wasm:Ensure wasm32-wasip1 rust-std is installed (no cargo / grep)
#   - ci.yml:wasm:Run golden + accuracy + simd_parity + unit tests via wasmtime (no cargo / grep)
#   - security-audit.yml:audit:Install cargo-audit (needs network / runner-only)
#   - security-audit.yml:deny:Install cargo-deny (needs network / runner-only)
#   - security-audit.yml:coverage:Run coverage (docs.rs feature set) (needs network / runner-only)
#   - fuzz.yml:fuzz:Install cargo-fuzz (needs network / runner-only)
#   - fuzz.yml:fuzz:Build fuzz target (needs network / runner-only)
#   - fuzz.yml:fuzz:Set fuzz duration (no cargo / grep)
#   - fuzz.yml:fuzz:Replay committed seeds (blocking) (needs network / runner-only)
#   - fuzz.yml:fuzz:Run fuzz target (time-boxed) (continue-on-error)
#   - fuzz.yml:fuzz:Report crash (informational) (no cargo / grep)

need actionlint "brew install actionlint"
need cargo-audit "cargo install cargo-audit --locked"
need cargo-deny "cargo install cargo-deny --locked"
need cargo-hack "cargo install cargo-hack --locked"
need cargo-machete "cargo install cargo-machete --locked"
need cargo-semver-checks "cargo install cargo-semver-checks --locked"
has_toolchain 1.85 || { echo "missing toolchain 1.85 (rustup toolchain install 1.85)" >&2; exit 1; }

step "ci.yml / wasm: Build tests (wasm32-wasip1)"
rustup target list --installed | grep -q '^wasm32-wasip1$' || rustup target add wasm32-wasip1
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo test --features "$ALL_FEATURES" --target wasm32-wasip1 --no-run )

step "ci.yml / wasm: Run golden + accuracy + simd_parity + unit tests via wasmtime"
if command -v wasmtime >/dev/null 2>&1; then
  for t in golden accuracy simd_parity alice_det_math; do
    WASM_BIN=$(find target/wasm32-wasip1/debug/deps -name "${t}-*.wasm" -not -name '*.d' | head -1)
    echo "Executing: $WASM_BIN"
    wasmtime "$WASM_BIN"
  done
else
  echo "skip: wasmtime not installed (CI runs it)"
fi

step "ci.yml / clippy: clippy (default, all targets)"
relint
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo clippy --all-targets -- -D warnings )

step "ci.yml / clippy: clippy (docs.rs feature set, all targets)"
relint
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo clippy --all-targets --features "$ALL_FEATURES" -- -D warnings )

step "ci.yml / clippy: clippy (no_std lib)"
relint
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo clippy --lib --no-default-features -- -D warnings )

step "ci.yml / no_std: Build rlib for a target without std"
rustup target list --installed | grep -q '^thumbv7em-none-eabihf$' || rustup target add thumbv7em-none-eabihf
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo rustc --lib --no-default-features --crate-type rlib --target thumbv7em-none-eabihf )

step "ci.yml / no_std: Build rlib for a target without std (simd)"
rustup target list --installed | grep -q '^thumbv7em-none-eabihf$' || rustup target add thumbv7em-none-eabihf
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo rustc --lib --no-default-features --features simd --crate-type rlib --target thumbv7em-none-eabihf )

step "ci.yml / msrv: cargo check on MSRV (lib, default features)"
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo +1.85 check --lib --locked )

step "ci.yml / msrv: cargo check on MSRV (lib, docs.rs feature set)"
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo +1.85 check --lib --locked --features "$ALL_FEATURES" )

step "ci.yml / msrv: cargo build on MSRV (no_std rlib, bare-metal target)"
rustup target list --installed --toolchain 1.85 | grep -q '^thumbv7em-none-eabihf$' || rustup target add thumbv7em-none-eabihf --toolchain 1.85
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo +1.85 rustc --lib --locked --no-default-features --crate-type rlib --target thumbv7em-none-eabihf )

step "ci.yml / feature-powerset: Powerset (all depths)"
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo hack check --lib --feature-powerset )

step "ci.yml / doc: cargo doc (default)"
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; RUSTDOCFLAGS="-Dwarnings" cargo doc --lib --no-deps )

step "ci.yml / doc: cargo doc (docs.rs feature set)"
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; RUSTDOCFLAGS="-Dwarnings" cargo doc --lib --no-deps --features "$ALL_FEATURES" )

step "ci.yml / fmt: Check formatting"
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo fmt -- --check )

step "ci.yml / actionlint: actionlint"
actionlint .github/workflows/*.yml

step "security-audit.yml / deny: cargo deny (all features)"
( export CARGO_TERM_COLOR="always" CARGO_NET_RETRY="5" CARGO_HTTP_MULTIPLEXING="false"; cargo deny --all-features check all )

step "security-audit.yml / unused-deps: cargo machete"
cargo machete

step "security-audit.yml / stub-guard: Detect todo! / unimplemented! / panic!(STUB)"
(
  export CARGO_TERM_COLOR="always" CARGO_NET_RETRY="5" CARGO_HTTP_MULTIPLEXING="false"
  set -eo pipefail
  hits=$(grep -rnE 'todo!\(|unimplemented!\(|panic!\([^)]*STUB' src/ --include="*.rs" || true)
  if [ -n "$hits" ]; then
    echo "❌ Stub / unimplemented / STUB panic detected (production path):"
    echo "$hits"
    exit 1
  fi
  echo "✓ No todo! / unimplemented! / panic!(STUB) in src/"
)

step "security-audit.yml / stub-guard: Detect dbg!() residual"
(
  export CARGO_TERM_COLOR="always" CARGO_NET_RETRY="5" CARGO_HTTP_MULTIPLEXING="false"
  set -eo pipefail
  hits=$(grep -rn 'dbg!(' src/ --include="*.rs" || true)
  if [ -n "$hits" ]; then
    echo "❌ dbg!() macro left in production code:"
    echo "$hits"
    exit 1
  fi
  echo "✓ No dbg!()"
)

step "security-audit.yml / stub-guard: Detect platform libm / mul_add calls in src/"
(
  export CARGO_TERM_COLOR="always" CARGO_NET_RETRY="5" CARGO_HTTP_MULTIPLEXING="false"
  set -eo pipefail
  hits=$(grep -rnE '\.(sin|cos|tan|asin|acos|atan|atan2|sinh|cosh|tanh|exp|exp2|ln|log|log2|log10|powf|powi|cbrt|hypot|mul_add|floor|ceil|round|trunc|fract)\(' src/ --include="*.rs" \
    | grep -vE '^\S+:\s*//' \
    | grep -vE 'src/ops\.rs:[0-9]+:\s+x\.sqrt\(\)' \
    | grep -vE 'tests|assert|x\.round\(\)|y\.round\(\)|x\.sqrt\(\)|y\.sqrt\(\)|f64::|f32::' \
    || true)
  if [ -n "$hits" ]; then
    echo "❌ platform libm / mul_add call in src/ (breaks the bit-exact guarantee):"
    echo "$hits"
    exit 1
  fi
  echo "✓ No platform libm / mul_add in src/ (outside ops::sqrt std path and test modules)"
)

step "security-audit.yml / semver-checks: check-release vs crates.io (skipped until the first publish)"
if cargo search alice-det-math --limit 1 2>/dev/null | grep -q '^alice-det-math = '; then
  ( export CARGO_NET_RETRY="5" CARGO_HTTP_MULTIPLEXING="false"; cargo semver-checks check-release --package alice-det-math --only-explicit-features --features std,simd )
else
  echo "skip: alice-det-math is not on crates.io yet"
fi

step "fuzz.yml / build every fuzz target (nightly; the replay needs the runner)"
if has_toolchain nightly && cargo +nightly fuzz --version >/dev/null 2>&1; then
  (cd fuzz && cargo +nightly fuzz build)
else
  echo "skip: nightly / cargo-fuzz not installed" >&2
fi

if [[ $quick -eq 1 ]]; then
  echo; echo "preflight --quick OK (test / bench suites skipped)"; exit 0
fi

step "ci.yml / test: Test (default features)"
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo test )

step "ci.yml / test: Test (docs.rs feature set)"
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo test --features "$ALL_FEATURES" )

step "ci.yml / test: Test (no_std, software sqrt)"
( export CARGO_TERM_COLOR="always" ALL_FEATURES="std,simd"; cargo test --no-default-features --features simd )

# ci.yml / simd-paths: the x86_64 lanes (sse2-only / avx2+fma) need an x86_64
# host; on any host the `native` lane is reproducible and proves no fma contraction.
step "ci.yml / simd-paths: Test (native)"
( export RUSTFLAGS="-C target-cpu=native" ALL_FEATURES="std,simd"; cargo test --features "$ALL_FEATURES" --target-dir target/native )
if [[ "$(uname -m)" == "x86_64" ]]; then
  step "ci.yml / simd-paths: Test (sse2-only)"
  ( export RUSTFLAGS="-C target-feature=-avx2,-avx,-fma,-sse4.1" ALL_FEATURES="std,simd"; cargo test --features "$ALL_FEATURES" --target-dir target/sse2 )
  step "ci.yml / simd-paths: Test (avx2-fma)"
  ( export RUSTFLAGS="-C target-feature=+avx2,+fma" ALL_FEATURES="std,simd"; cargo test --features "$ALL_FEATURES" --target-dir target/avx2 )
elif [[ "$(uname -s)" == "Darwin" ]] && arch -x86_64 /usr/bin/true 2>/dev/null; then
  # Apple Silicon: Rosetta runs a real x86_64 build, which is what caught the
  # x86-vs-ARM default-NaN sign difference before it was a CI red twice over
  step "ci.yml / test (x86_64 via Rosetta): golden + simd_parity + accuracy"
  for t in golden simd_parity accuracy; do
    bin=$(cargo test --features std,simd --target x86_64-apple-darwin --test "$t" --no-run 2>&1 | grep -oE "target/x86_64-apple-darwin/debug/deps/${t}-[a-f0-9]+" | head -1)
    arch -x86_64 "$bin"
  done
  step "ci.yml / test (x86_64 via Rosetta, no_std software sqrt): golden"
  bin=$(cargo test --no-default-features --features simd --target x86_64-apple-darwin --test golden --no-run 2>&1 | grep -oE "target/x86_64-apple-darwin/debug/deps/golden-[a-f0-9]+" | head -1)
  arch -x86_64 "$bin"
else
  echo "skip: sse2-only / avx2-fma lanes need an x86_64 host (CI runs them)"
fi

step "security-audit.yml / audit: cargo audit"
( export CARGO_TERM_COLOR="always" CARGO_NET_RETRY="5" CARGO_HTTP_MULTIPLEXING="false"; cargo audit --deny yanked )

echo; echo "preflight OK"
